name: Injection Test

on:
  issues:
    types: [opened]

jobs:
  secure:
    runs-on: ubuntu-latest
    steps:
      - name: Secure step
        env:
          ISSUE_TITLE: ${{ github.event.issue.title }}
        run: |
          echo "New issue title is: $ISSUE_TITLE"
